height: 178
build: Lean, slightly underweight due to neglecting physical health in favor of work.
hair: Short, dark brown, usually unkempt.
eyes: Pale blue, with a sharp, piercing gaze that reflects his intense focus.
clothing_style: Ethan tends to dress simply, favoring comfortable, functional clothing like jeans and hoodies. He’s not concerned with fashion and often wears the same few outfits on rotation.
