name: Ethan Hettinger
age: 25
occupation_headline: Software Engineer/AI Developer
education_headline: Bachelor's Degree in Computer Science from MIT (Graduated at 21, with honors). Specialization in Artificial Intelligence, Machine Learning, and Neural Networks
