name: Olivia Stroustrup
age: 27
occupation_headline: Cognitive Neuroscientist / Behavioral Analyst
education_headline: PhD in Cognitive Neuroscience from Stanford University. Specialization in Neural networks, human-computer interaction, and the impact of AI on human cognition.
